scielomanager/journalmanager/tests/tests_forms.py
scielomanager/journalmanager/views.py

FIXES: #1053
``userprofileformset.save()`` como o campo: ``userprofile-0-email_notifications`` desmarcado, fazia com que o save() do formset, tentase criar um novo UserProfile para o novo usário (que já conta com um profile no momento da criação).
Então a solução tipo: "work-around" é não salvar o formset, mas recuperar os campos modificados, e fazer o ``setatt(...)`` desses campos no user profile correto.
Foi adicionado um test com a situação de salvar um novo user com o campo unchecked, para reproduzir o erro e garantir que não aconteça de novo.

FIX: IntegrityError quando é criado um novo usuário - #1053

---

scielomanager/export/templates/export/markup_files.html
scielomanager/journalmanager/views.py

FIXES: #1066 
- adiciono validação js para confirmar que o ajax, recebe o dado do journal.
- caso o ajax retorne algum erro, notifica o usuário. antes só via o loading spinner ad infinitum
- na view do ajax: se não vem algum valor no ``journal_id``, retorna um HTTP 400 - Bad Request.

#1066 - Internal Server Error: /journal/ajx/ajx1/

---

.travis.yml
scielomanager/scielomanager/settings.py

O arquivo de configurações deve ser declarado por meio da variável de
ambiente SCIELOMANAGER_SETTINGS_FILE. A ausência dessa variável
levantará um RuntimeError.
Idealmente, o arquivo de configuração deve ser alocado fora da estrutura
do pacote da aplicação, apenas com permissão de leitura.

Permitir configurações externas ao pacote da app

---

Makefile

Task que compila todos os módulos do projeto. O objetivo é de tornar
explícita a etapa de compilação, para que seja realizada por um usuário
com privilégios administrativos, e não mais pelo servidor de aplicação.
Outros ajustes foram realizados no Makefile para reduzir efeitos
colaterais, como por exemplo a execução da task "clean".

Task *compile* no Makefile

---

scielomanager/editorialmanager/models.py
scielomanager/editorialmanager/tests/test_forms.py

PR simples para manter os membros do corpo editorial em ordem alfabética. Tk #1099

Ordena o corpo editorial por ordem alfabética

---

scielomanager/journalmanager/tasks.py

Em levantamento realizado em todos os XMLs SPS da Revista de Saúde Pública,
10% apresentam inversão na identificação do ISSN impresso, e 12% na
identificação do ISSN eletrônico. Também foram levantados dados da ABEM
e ABC, entretanto nenhuma apresentou a inversão.
Por tratar-se então de uma condição excepcional, a tentativa de
associação de XMLs que contém a inversão será realizada apenas caso a
primeira tentativa falhe, onerando assim apenas os casos excepcionais
com maior custo de consulta ao banco de dados.

Fixes #1126 - Corrige falha na associação entre artigos e periódicos.

---

scielomanager/scielomanager/static/js/modal.js

resolver o glitch quando é aberto um modal que contém um form
- na página do board, no editorial manager: abrir um modal clickando em: **add new member**
- na página do board, no editorial manager: abrir um modal clickando em: **edit** (botão azul) do lado de algum Board Member cadastrado.

fix para disparar eventos após a carga de conteúdo "remoto" nos modals

---

requirements.txt
scielomanager/editorialmanager/models.py

Ref #1153. 
Para que essa atividade é necessário atualizar o django-countries==3.0.1(atual) para django-countries==3.3.

Alterando param no CountryField() para que tenhamos um valor vazio no componente da interface.

---

docs/dev/rpc_spec/getScanArticlesBatch.rst
docs/dev/rpc_spec/scanArticles.rst
scielomanager/journalmanager/tasks.py
scielomanager/scielomanager/connectors/__init__.py
scielomanager/scielomanager/connectors/exceptions.py
scielomanager/scielomanager/connectors/storage.py
scielomanager/scielomanager/settings.py
scielomanager/scielomanager/tests/tests_connectors.py
scielomanager/scielomanager/tools.py
scielomanager/thrift/scielomanager.thrift
scielomanager/thrift/server.py

Definidas as funções *scanArticles* e *getScanArticlesBatch*, conforme
as especificações:
- scanArticles: docs/dev/rpc_spec/scanArticles.rst
- getScanArticlesBatch: docs/dev/rpc_spec/getScanArticlesBatch.rst
A implementação das funções envolve consultas ao Elasticsearch, o que
provocou uma reorganização dos códigos de conexão que foram movidos para
o pacote `scielomanager.connectors`. A proposta é que esse pacote agrupe
classes que representem o link entre o projeto e componentes externos -
no caso o projeto e o Elasticsearch. Além disso também foi definido o
adaptador `scielomanager.connectors._Elasticsearch`, implementando uma
interface de mais alto-nível em relação à lib `elasticsearch-py`.
Ainda sobre Elasticsearch, também foi realizada uma alteração do schema de
documentos do tipo …

Funções de recuperação de registros na interface RPC Thrift.

---

scielomanager/journalmanager/tasks.py
scielomanager/scielomanager/connectors/__init__.py
scielomanager/scielomanager/connectors/article_mapping.json
scielomanager/scielomanager/management/commands/es.py
scielomanager/scielomanager/settings.py
scielomanager/thrift/scielomanager.thrift

O utilitário conta com dois comandos:
- putmapping: para definir ou atualizar o mapping de um tipo
- createindex: para criar um índice e definir o mapping do tipo
Além dessas, as seguintes modificações também foram realizadas:
- Definição do mapping para o o doctype `article`
- Inclusão do campo `timestamp` no mapping `article`
- Inclusão do campo `timestamp` na struct `Article`, da interface
Thrift

Inclusão do utilitário de gerenciamento `./manage.py es`

---

requirements.txt
scielomanager/remove_tables_waffle_app.sql
scielomanager/scielomanager/settings.py

FIXES: #1091
0. fazer backup do DB!!
1. atualizar o codigo ``git pull ...``
2. make test
3. remover o pacote do ambiente/sistema: ``pip uninstall django-waffle``
4. aplicar snippet SQL para eliminar tabelas do banco: ``cat remove_tables_waffle_app.sql | psql MANAGER_DB_NAME  -U MANAGER_DB_USER``
5. make test
6. :beers: cheers! :beers:

Remover app waffles

---

scielomanager/journalmanager/models.py
scielomanager/journalmanager/tests/tests_models.py
scielomanager/journalmanager/tests/xml_samples/0034-8910-rsp-48-2-0216.xml

A chave de domínio passou a integrar os valores de fpage/@seq e
article-id[@pub-id-type="other"] a fim de desambiguar documentos que
compatilham numeração de página e artigos AOP. Essa alteração corrige um
bug que considerava artigos AOP do mesmo ano como duplicados.
Além disso, também foi alterada a lógica de inferência de artigos AOP
pelo SciELO Manager. A explicação que segue está descrita na docstring
do método `journalmanager.models.Article._get_is_aop`:
Diferentemente das regras publicadas no SciELO PS, o SciELO
Manager considera AOP (ahead-of-print) os artigos que
apresentam o número identificador de AOP no elemento
``//article-meta/article-id[pub-id-type="other"]``.
O SciELO Manager adota uma abordagem não-opinionada acerca da
estrutura de publicação do periódico, portanto não …

Microafinação na chave de domínio das entidades `Article`.

---

scielomanager/scielomanager/settings.py

Os logs foram configurados de maneira que *loggers* não definidos sejam propagados e tratados pelo *root logger*. 
O comportamento definido foi:
* 2 handlers: 1) console -> logging.StreamHandle, que não define o nível de log e 2) mail_admins -> django.utils.log.AdminEmailHandler, que trata apenas logs de nível ERROR.
* 5 loggers: 1) raíz, que captura todos os erros de nível ERROR do projeto e suas dependências, 2) django.request, que envia email para os admins com traceback em erros em request/response, 3)4)5) que capturam mensagens de nível INFO para serviços da app e o packtools.
Também defini um formato para a mensagem de log que penso ser bom: ``'%(asctime)s %(name)s[%(process)d] [%(levelname)s] %(message)s'``

Configuração padrão de logs

---

scielomanager/journalmanager/tasks.py
scielomanager/scielomanager/settings.py

Todas as tasks que realizam consultas ao banco de dados por grandes
lotes de entidades tipo `journalmanager.models.Article`, e em seguida
disparam novas tasks passando o valor do seu atributo `pk` como
argumento estão vazando memória. A solução adotada não resolve a causa
raíz (ciclo de referências nas instâncias), mas acabou sendo a mais
adequada para o caso:
A projeção das consultas deve apresentar apenas o atributo `pk`.

Correção de vazamento de memória em tasks da app `journalmanager`.

---

requirements.txt
scielomanager/health/checks.py
scielomanager/health/management/commands/healthd.py
scielomanager/journalmanager/admin.py
scielomanager/journalmanager/modelmanagers.py
scielomanager/journalmanager/models.py
scielomanager/journalmanager/tasks.py
scielomanager/journalmanager/views.py
scielomanager/maintenancewindow/models.py
scielomanager/scielomanager/settings.py
scielomanager/scielomanager/settings_local.include-TEMPLATE
scielomanager/scielomanager/settings_tests.py
scielomanager/scielomanager/utils/modelmanagers/base.py

FIXES: #1195
- faltaria reformar ``scielomanager/utils/modelmanagers/base.py`` mas pode ser uma tarefa independente, junto com a reorganização dos modelmanagers.
- lembrar que tem que desinstalar as dependencias removidas do ``requirements.txt`` com  ``pip uninstall ...``

#1195 - remover django-cache-machine

---

scielomanager/journalmanager/migrations/0025_auto__add_articlecontrolattributes.py
scielomanager/journalmanager/migrations/0026_migrate_article_control_attributes.py
scielomanager/journalmanager/migrations/0027_auto__del_field_article_es_updated_at__del_field_article_es_is_dirty__.py
scielomanager/journalmanager/models.py
scielomanager/journalmanager/tasks.py
scielomanager/journalmanager/tests/tests_models.py

Os atributos de controle foram migrados para um tipo de entidade
próprio, simplificando a implementação. A vantagem mais atraente dessa
nova implementação é que as regiões críticas -- protegidas por mutexes
-- do módulo *journalmanager.tasks* deixaram de existir.

Atributos de controle para entidades tipo *Article*.

---

docs/dev/rpc_spec/addArticleAsset.rst
docs/dev/rpc_spec/errno.rst
scielomanager/journalmanager/migrations/0028_auto__add_articleasset.py
scielomanager/journalmanager/models.py
scielomanager/journalmanager/tasks.py
scielomanager/journalmanager/tests/tests_tasks.py
scielomanager/thrift/scielomanager.thrift
scielomanager/thrift/server.py

Closes #1243 
Foi definido o tipo de entidade ``ArticleAsset`` e a função ``addArticleAsset``
na interface thrift, cuja implementação segue a especificação descrita
em ``docs/dev/rpc_spec/addArticleAsset.rst``.
Os ativos são armazenados no diretório base definido na diretiva
``MEDIA_ROOT``, seguidos da estrutura
``articles/<aid>/assets/<filename>``.

Armazenamento de ativos estáticos vinculados aos artigos.

---

scielomanager/journalmanager/templates/journalmanager/article_detail.html
scielomanager/journalmanager/templates/journalmanager/article_list.html
scielomanager/journalmanager/views.py

* Agrupamento por ``HEAD_SUBJECT`` na listagem de artigos do número;
* Removida restrição que impedia a pré-visualização em HTML de artigos
em AOP;
* Pré-visualização aparece primeiro do conteúdo XML, pois é mais *user
friendly*, nos detalhes de um artigo;
* Ajuste na view-function para tornar o código mais idiomático.

Pequenos ajustes na visualização dos artigos.

---

scielomanager/journalmanager/models.py
scielomanager/journalmanager/templates/journalmanager/add_issue.html
scielomanager/journalmanager/tests/tests_models.py
scielomanager/validator/tests/doubles.py

- troca no __unicode__ do modelo journalmanager.Section para um pipe no lugar de barra;
- ajustes na UI para facilitar a seleção no drop down, agora como widget: chosen;
- ajuste no unit test, por causa da troca de slash por pipe;
- ajuste no double importado nos unit test da app validator, para resolver o erro:
> Error when calling the metaclass bases: function() argument 1 must be code, not str
Que apareceu depois da atualização do packtools (eu acho)

#1160 - Trocar o separador dos títulos de seções

---

scielomanager/api/resources_v1.py
scielomanager/api/resources_v2.py

Existen valores nulos en el atributo use_license por lo que ocurre el siguiente error al hacer una petición a issues ```http://manager.scielo.org/api/v1/issues/?collection=mexico&format=json```
````
{
"error": "The model '<Issue: 41 (1)>' has an empty attribute 'use_license' and doesn't allow a null value."
}
```

Permitir valores nulos en use_license

---

scielomanager/journalmanager/migrations/0029_auto__add_articlehtmlrendition__add_unique_articlehtmlrendition_articl.py
scielomanager/journalmanager/models.py
scielomanager/journalmanager/tasks.py
scielomanager/journalmanager/tests/tests_tasks.py
scielomanager/journalmanager/views.py

Closes #1259
A contrução dos HTMLs é executada automaticamente após a criação ou
modificação de instâncias de ``journalmanager.models.Article``. A rotina
responsável pela operação é a
``journalmanager.tasks.create_article_html_renditions``, que pode ser
invocada de maneira sincrona ou assíncrona. Não foram inseridos botões
de ação para a reconstrução dos HTMLs por falta de definição dos
requisitos.
Esse pull request modifica a estrutura de diretórios definida no ticket #1244 para lidar melhor com as limitações impostas pelos sistemas de arquivos em relação ao número de subdiretórios e arquivos em um único inode.

Construção dos HTMLs dos artigos

---

docs/dev/rpc_spec/addArticle.rst
scielomanager/journalmanager/tasks.py
scielomanager/journalmanager/tests/tests_tasks.py
scielomanager/thrift/scielomanager.thrift
scielomanager/thrift/server.py

Closes #1264.
A solução proposta modifica a assinatura da função ``addArticle``, da
interface thrift, para receber um segundo argumento posicional chamado
``overwrite`` que indica se é para o servidor tratar duplicatas como
pedidos de substituição.

Capacidade de sobrescrever artigos já cadastrados.

---

scielomanager/api/resources_v1.py
scielomanager/api/tests_resources_v1.py

Atividade realizadas nesse PR: 
Corrigi erro encontrado na API V1 do SciELO Manager ao acessar um periódico que pertence a mais de uma coleção, msg de error:
```
{
error_message: "Sorry, this request could not be processed. Please try again later."
}
```
Alterado a API para garantir que o param ``collection`` seja obrigatório, removido a lógico que obrigava que o periódico seja o default active collection do usuário que acessa a API.
* Alterado o modulo resources_v1.py
* Ajustado teste existentes para essa situação 
* Adicionado testes para garantir retorno no HTTP 400 (BadRequest) 👍

Garantido que não tenha erro ao acesso a API v1 quando uma revista pertence a mais de uma coleção.

---

scielomanager/export/markupfile.py
scielomanager/export/tests/tests_markupfiles.py

#1286 - Trocar title_iso por short_title nos arquivos exportados *_issue.mds

---

scielomanager/export/markupfile.py
scielomanager/export/tests/tests_markupfiles.py

Aplica as modificações descritas no ticket
https://github.com/scieloorg/scielo-manager/issues/1286
Fixes #1413

Normaliza dados do periódico para número regular e AOP nos pacotes do Markup.
