scieloorg/scielo-manager

requirements.txt, scielomanager/journalmanager/models.py, scielomanager/journalmanager/tasks.py, scielomanager/scielomanager/custom_fields.py, scielomanager/scielomanager/settings.py
- adicionado no requirements o cliente oficial do elasticsearch
- adicionado signal post_save do Article, para executar a task
- FIX no custom_field
- nova task para enviar o XML e metadados para o elasticsearch criar o indice
=> integração do manager com o elasticsearch

scielomanager/journalmanager/templates/journalmanager/article_list.html
=> #1078 - interface quebrada na listagem de artigos de um fascículo

.travis.yml
Tentativa de colocar ambas as variáveis de ambiente na mesma linha
=> Tentativa #1 de consertar o travis

scielomanager/editorialmanager/tests/modelfactories.py, scielomanager/editorialmanager/tests/test_forms.py, scielomanager/editorialmanager/views.py, scielomanager/journalmanager/models.py, scielomanager/journalmanager/views.py
Nesse PR estou ajustando para que o usuário com o perfil trainee possa acessar e modificar as opções no corpo editorial.
Ref.: #1104
=> Permissão de acesso ao corpo editorial aos usuários com perfil trainee 

scielomanager/editorialmanager/templates/board/board_list_data.html
=> Alteração simples da ordem do e-mail na lista do corpo editorial.

scielomanager/journalmanager/views.py
Corrigido bug que quebrava a funcionalidade de busca por um periódico
pré-existente, no momento de adicionar um novo a uma coleção.
O bug se deu por conta de o *mimetype* não ter sido explicitado na
*view-function* que interage com o componente de interface do usuário,
via ajax.
----
Atualização: Além disso, também realizei um ajuste de estilo no corpo das view-functions para aumentar a legibilidade.
=> Fixes #1130 - Bug no componente de seleção dos periódicos.

scielomanager/journalmanager/tasks.py, scielomanager/scielomanager/settings.py
Deixar o nome do índice configurável
- ``settings.py``
- ``scielomanager/tasks.py``
- FIX: #1133
=> Identificador do índice no ES deve ser configurável

scielomanager/editorialmanager/templates/board/board_list.html, scielomanager/editorialmanager/templates/board/board_list_data.html, scielomanager/editorialmanager/templates/includes/journal_detail_info.html, scielomanager/editorialmanager/tests/test_pages.py, scielomanager/editorialmanager/views.py
=> Exportação do Board como CSV: observações e melhorias

scielomanager/editorialmanager/templates/board/board_list.html, scielomanager/editorialmanager/templates/board/board_list_data.html, scielomanager/editorialmanager/templates/includes/add_member_form_loaded_callbacks.js, scielomanager/scielomanager/static/js/modal.js
Ref: #1143 
Com a ajuda especial do @jfunez realizamos essa tarefa de forma fácil e simples.
=> Mantendo o formulário de add member maximizado

requirements.txt
FIX: #1089
Executar: ``pip install --upgrade -r requirements.txt``
=> versão de Django desatualizada #1089

scielomanager/accounts/templates/accounts/my_account.html, scielomanager/editorialmanager/templates/board/board_member_delete.html, scielomanager/editorialmanager/templates/board/board_member_edit.html, scielomanager/editorialmanager/templates/journal/edit_journal.html, scielomanager/journalmanager/templates/journalmanager/add_user.html, scielomanager/journalmanager/templates/journalmanager/editor.html, scielomanager/journalmanager/templates/journalmanager/user_list.html, scielomanager/scielomanager/static/js/modal.js, scielomanager/scielomanager/templates/base_lv0.html
=> Erro ao exibir mensagem traduzida na função *Add new member* #1161

docs/dev/rpc_spec/getInterfaceVersion.rst, scielomanager/thrift/scielomanager.thrift, scielomanager/thrift/server.py
=> Implementação da função `getInterfaceVersion()` na interface Thrift.

scielomanager/journalmanager/tasks.py
Maiores detalhes estão no ticket #1183
=> Tasks para reconstrução da chave de domínio dos artigos

scielomanager/scielomanager/static/css/codemirror/addon/dialog/dialog.css, scielomanager/scielomanager/static/css/codemirror/lib/codemirror.css, scielomanager/scielomanager/static/js/codemirror/addon/dialog/dialog.js, scielomanager/scielomanager/static/js/codemirror/addon/fold/foldcode.js, scielomanager/scielomanager/static/js/codemirror/addon/fold/foldgutter.js, scielomanager/scielomanager/static/js/codemirror/addon/search/search.js, scielomanager/scielomanager/static/js/codemirror/addon/search/searchcursor.js, scielomanager/scielomanager/static/js/codemirror/lib/codemirror.js, scielomanager/scielomanager/static/js/codemirror/mode/xml/xml.js
Nova versão de CodeMirror: 5.6 (com addons atualizados também).
FIX: #1198
=> #1198 - Atualização de dependencia (js) Codemirror

scielomanager/accounts/templates/accounts/unauthorized.html, scielomanager/editorialmanager/templates/journal/journal_detail.html, scielomanager/editorialmanager/templates/journal/journal_list.html, scielomanager/journalmanager/templates/journalmanager/includes/titleformset.html, scielomanager/journalmanager/templates/journalmanager/journal_list.html, scielomanager/journalmanager/views.py, scielomanager/scielomanager/custom_fields.py
=> #1203 - corrigir textos

scielomanager/journalmanager/templates/journalmanager/add_pressrelease.html
=> #930 - Bug na página do Press Release

scielomanager/journalmanager/templates/journalmanager/add_pressrelease.html
=> #929 - Bug no botão **Preview as HTML**

scielomanager/journalmanager/migrations/0004_auto__add_articleslinkage__add_field_article_articles_linkage_are_pend.py, scielomanager/journalmanager/migrations/0005_set_doi_and_articletype_attrs.py, scielomanager/journalmanager/models.py, scielomanager/journalmanager/tasks.py, scielomanager/journalmanager/tests/modelfactories.py, scielomanager/journalmanager/tests/tests_models.py, scielomanager/journalmanager/tests/tests_tasks.py, scielomanager/journalmanager/tests/xml_samples/0034-8910-rsp-48-2-0216_related.xml, scielomanager/scielomanager/celery.py, scielomanager/scielomanager/custom_fields.py
Closes #1216.
* Adicionado o atributo de controle *Article.articles_linkage_is_pending*
para coordenar a operação das tasks periódicas:
``journalmanager.tasks.link_article_with_their_related`` e
``journalmanager.tasks.process_related_articles``, para a identificação e
estabelecimento das associações entre os artigos.
* Adicionada configuração padrão do agendador de tarefas.
* Scripts de migração de dados.
=> Relacionamento recursivo entre entidades do tipo Article

scielomanager/journalmanager/tasks.py, scielomanager/scielomanager/connectors/article_mapping.json, scielomanager/thrift/scielomanager.thrift, scielomanager/thrift/server.py
=> Modifica a interface thrift para conter os campos *links_to* e *referrers*

scielomanager/api/resources_v1.py, scielomanager/api/resources_v2.py, scielomanager/api/tests_resources_v1.py, scielomanager/api/tests_resources_v2.py, scielomanager/journalmanager/migrations/0006_auto__del_datachangeevent.py, scielomanager/journalmanager/models.py, scielomanager/journalmanager/tests/modelfactories.py, scielomanager/journalmanager/views.py, scielomanager/scielomanager/urls.py
=> Closes #1223 - Removido o tipo de entidade *DataChangeEvent*

scielomanager/journalmanager/tasks.py, scielomanager/scielomanager/connectors/__init__.py, scielomanager/scielomanager/connectors/article_mapping.json, scielomanager/scielomanager/connectors/storage.py, scielomanager/scielomanager/management/commands/es.py
Ainda relacionado ao ticket #1222.
* Modificações para acomodar os atributos `links_to` e `referrers`.
* Adicionado os comandos `./manage.py es deleteindex` e `./manage.py es reindex`.
=> Ajusta pontos da interação com o Elasticsearch

docs/dev/issues-api.rst, scielomanager/api/resources_v1.py, scielomanager/api/resources_v2.py, scielomanager/api/tests_resources_v1.py, scielomanager/api/tests_resources_v2.py
=> Licencia de uso incluida en la respuesta de la API para fascículos

scielomanager/journalmanager/tasks.py
Relacionado ao #1248.
A falta de padronização para o preenchimento do elemento
``/article/front/article-meta/issue`` torna difícil o rastreio do
respectivo fascículo no SciELO Manager, especialmente para os casos de
suplementos e números especiais.
Por hora, a função ``journalmanager.tasks.link_article_to_issue``
tratará apenas o vínculo entre artigos e fascículos regulares.
=> Evitando o vínculo entre artigos e números para suplementos e especiais.

requirements.txt, scielomanager/journalmanager/views.py, scielomanager/validator/tests/doubles.py, scielomanager/validator/utils.py, scielomanager/validator/views.py
=> Atualiza a versão da dependência *packtools*.

scielomanager/journalmanager/models.py, scielomanager/journalmanager/tests/tests_models.py
=> Corrige bug na criação de seções de periódicos com acrônimo unicode.

scielomanager/journalmanager/models.py, scielomanager/journalmanager/tasks.py, scielomanager/journalmanager/tests/modelfactories.py, scielomanager/journalmanager/tests/tests_models.py, scielomanager/journalmanager/tests/tests_tasks.py
=> Move a inicialização de atributos de Article().save para Article.parse.

scielomanager/journalmanager/forms.py
Fixes #1267.
Alguns fascículos de determinado periódico podem apresentar valores
idênticos para os atributos: ``volume``, ``number`` e
``publication_year``. Por exemplo, a RSP possui os fascículos: 2016 v50
suppl 1 e 2016 v50 volume issue. Ao cadastrar ambos os fascículos na ordem
apresentada, o segundo falha alegando que o fascículo já existe.
=> Corrige bug na validação do form do fascículo.

scielomanager/accounts/views.py, scielomanager/editorialmanager/views.py, scielomanager/journalmanager/views.py
=> Corrige na decodificação de string em ajx_add_journal_to_user_collection.

scielomanager/gevent_wsgi.py
Foi criado um novo script wsgi que realiza todos os patches antes da instanciação da aplicação.
=> Fixes #1284 - App WSGI assíncrona com gevent

scielomanager/editorialmanager/templates/board/role_type_translate.html, scielomanager/editorialmanager/templates/includes/journal_detail_info.html, scielomanager/editorialmanager/templates/journal/edit_journal.html, scielomanager/journalmanager/choices.py, scielomanager/journalmanager/forms.py, scielomanager/journalmanager/models.py, scielomanager/journalmanager/templates/journalmanager/add_issue.html, scielomanager/journalmanager/templates/journalmanager/add_journal.html, scielomanager/journalmanager/templates/journalmanager/add_pressrelease.html, scielomanager/journalmanager/templates/journalmanager/add_section.html, scielomanager/journalmanager/templates/journalmanager/add_sponsor.html, scielomanager/journalmanager/templates/journalmanager/add_user.html, scielomanager/journalmanager/templates/journalmanager/includes/form_field_row.html, scielomanager/scielomanager/locale/en_US/LC_MESSAGES/django.po, scielomanager/scielomanager/locale/es_ES/LC_MESSAGES/django.po, scielomanager/scielomanager/locale/pt_BR/LC_MESSAGES/django.po
=> Tornando alguns labels traduzivéis :-()

scielomanager/scielomanager/locale/es_ES/LC_MESSAGES/django.po
Atualização do idioma Espanhol
=> Update es translation

docs/dev/exporttoisis.rst
Estava lendo a documentação e encontrei alguns erros de digitação no texto. Daí já aproveitei o tempo pra editar.
=> Corrigindo erros no texto.

scielomanager/journalmanager/migrations/0033_update_issue_label.py, scielomanager/journalmanager/models.py, scielomanager/journalmanager/tests/tests_models.py
Fixes #1302
ATENÇÃO: Esse patch inclui migração de dados.
=> Exclui caractere "ponto" na representação textual de números especiais.
